<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/09/20 14:00:46

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=auswonder_travel',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
